version: "3.8"
services:
  api:
    build: "./"
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - RSC_SHEETS_API_TOKEN

  db:
    image: "postgres:12.4"
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
